### ISSUE TITLE
ESP32-Oscilloscope CYD issues 

### ISSUE THREAD

**Issue by BeqaMiqa** [ivan-rio/ESP32-Oscilloscope#1]
I've encountered some issues when using the Arduino IDE with this project.

1. **TFT_eSPI Library Compatibility**: The project only compiles correctly with TFT_eSPI version 2.5.33. Later versions cause compilation errors. After installing version 2.5.33, the code uploads successfully, but the oscilloscope trace line does not appear on the display. 

2. **Voltage Readings**: In the dropdown menu, the average voltage is displayed as ~24V, which is incorrect as I am not providing that voltage. The web installer works well overall, but the oscilloscope trace line shows 2V instead of the expected 3V during testing, even though the dropdown menu shows the correct voltage reading.

3. **Feature Suggestion**: It would be great if the web installer offered both light and dark mode options. To implement this, you would need to comment out line 115 in `User_Setup`:
    ```cpp
    #define TFT_INVERSION_ON
    // #define TFT_INVERSION_OFF
    ```

I hope this feedback helps improve the project. Thanks for your work!

**Comment by Rubendhes** [comment]
I agree with you my friend, I have encountered all these problems; I am not a programmer and I don't understand almost anything, but I think all these errors are intentional.

Thanks to you, I was able to make it work on my esp32 with 240 x 320 tft module.

I have found some bugs that are easily solved:

**TFT_eSPI Library Compatibility:** You can also use version 2.4.51, it is fully compatible.

**Touch buttons:** If you noticed that when you press the touch screen, the commands are backwards; you just have to change these symbols <> in the ESP32_Oscilloscope.ino file.
Example in the void touchpad_read() section, you should change it like this:

`void touchpad_read()
{
    if (ts.touched()) {
        TS_Point p = ts.getPoint();
        x = map(p.x, 220, 3850, 1, 320);
        y = map(p.y, 310, 3773, 1, 240);
        if(x > 110 && y < 60 && !touched) {
          btnmn = 1;
          touched = true;     }
        if(x < 210 && y < 60 && !touched) {
          btnpl = 1;
          touched = true; 
        }
        if(x > 110 && y > 160 && !touched) {
          btnbk = 1;
          touched = true;
        }
        if(x < 210 && y > 160 && !touched) {
          btnok = 1;
          touched = true;
        }        
    } else {
        touched = false;
        btnok = 0;
        btnbk = 0;
        btnpl = 0;
        btnmn = 0;
    }
}`

**The graph appears too high:** If the graph appears so high that it eventually becomes unseen, you will need to make some changes to the screen.ino file.
As I mentioned before, I am not a programmer so I don't know how to properly fix this error; but what I did to fix it fairly well was to replace this file with the one from the original post at https://github.com/Circuit-Digest/ESP32-Oscilloscope.
